### ISSUE TITLE
Proxying multiple containers which use same host port 

### ISSUE THREAD

**Issue by c-hri-s** [mikeburgh/subway#2]
Is there any way to proxy two containers which both use the same internal port?

For example I've got:

```
speedtest:
  image: henrywhitaker3/speedtest-tracker
  ports:
  - 8765:80
```

and

```
audiobookshelf:
  container_name: audiobookshelf
  image: ghcr.io/advplyr/audiobookshelf
  ports:
    - 13378:80
```

Obviously on my local network this works fine as the are port forwarded to different ports (http://internal.lan:8765 and http://internal.lan:13378), but internally they both run on port 80. 

Is there a way to have subway connect to both containers in order to proxy them?
